name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'This action is destructive. Type "destroy" to confirm.'
        required: true

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'destroy'

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ">=1.5.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get short-lived runner token
        id: get_token
        run: |
          TOKEN=$(curl -sX POST \
            -H "Authorization: Bearer ${{ secrets.ORG_RUNNER_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/orgs/find-your-bias/actions/runners/registration-token \
            | jq -r .token)
          echo "RUNNER_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_runner_token: ${{ env.RUNNER_TOKEN }}
          TF_VAR_aws_region: us-east-1
