name: Infra CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Checkout the infra repo (this repo)
      - name: Checkout infra
        uses: actions/checkout@v4

      # Checkout each microservice repo
      - name: Checkout vote
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/vote-microservice
          token: ${{ secrets.GITHUB_TOKEN }}
          path: vote

      - name: Checkout result
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/result-microservice
          token: ${{ secrets.GITHUB_TOKEN }}
          path: result

      - name: Checkout worker
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/worker-microservice
          token: ${{ secrets.GITHUB_TOKEN }}
          path: worker

      - name: Checkout ai-analyzer
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/ai-analyzer-microservice
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ai-analyzer

      # Gather all k8s-specifications manifests
      - name: Collect k8s-specifications manifests
        run: |
          mkdir all-k8s-specifications
          cp -r k8s-specifications/* all-k8s-specifications/ || true
          cp -r /home/ubuntu/actions-runner/_work/infra/infra/vote-microservice/k8s-specifications/* all-k8s-specifications/ || true
          cp -r /home/ubuntu/actions-runner/_work/infra/infra/result-microservice/k8s-specifications/* all-k8s-specifications/ || true
          cp -r /home/ubuntu/actions-runner/_work/infra/infra/worker-microservice/k8s-specifications/* all-k8s-specifications/ || true
          cp -r /home/ubuntu/actions-runner/_work/infra/infra/ai-analyzer-microservice/k8s-specifications/* all-k8s-specifications/ || true

      # Run your setup script
      - name: Run setup script
        run: bash setup.sh

      # Apply all manifests
      - name: Apply Kubernetes manifests
        run: kubectl apply -R -f all-k8s-specifications/

