name: Setup Infra and Deploy GitHub Runner

on:
  workflow_dispatch: # Manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest

    # Set AWS credentials as environment variables for the entire job
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }} # e.g., us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Get short-lived runner token
        id: get_token
        run: |
          TOKEN=$(curl -sX POST \
            -H "Authorization: Bearer ${{ secrets.ORG_RUNNER_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/orgs/find-your-bias/actions/runners/registration-token \
            | jq -r .token)
          echo $TOKEN
          echo "RUNNER_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: terraform 
        run: terraform init
      
      # - name: Terraform Plan
      #   working-directory: terraform
      #   run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve 
        env:
          # Pass the runner token specifically to Terraform
          TF_VAR_runner_token: ${{ env.RUNNER_TOKEN }}

